### ISSUE TITLE
Chartisan.php > protected function getDataset(string $name): ?ServerData

### ISSUE THREAD

**Issue by lolo3129** [Chartisan/PHP#1]
Hi,
why the result of this function Chartisan->getDataset is a ServerData and not a DatasetData ?
best regards,
Laurent

**Comment by ConsoleTVs** [comment]
Woah, great catch, do you want to perform this simple PR? Just click the edit button, change to `?DatasetData` and I'll accept the contribution!

**Comment by lolo3129** [comment]
done
