### ISSUE TITLE
syntax error, unexpected '$app' (T_VARIABLE), expecting ',' or ')'

### ISSUE THREAD

**Issue by Kirko95** [Chartisan/PHP#3]
I recently added chartisan to my project and when I deployed it on a shared host, it throws this error:
syntax error, unexpected '$app' (T_VARIABLE), expecting ',' or ')'

I have tried different things to fix it with no luck.
![Screenshot (146)](https://user-images.githubusercontent.com/29736097/100087763-3bcd9900-2e60-11eb-92bf-28418ca5930a.png)

**Comment by ConsoleTVs** [comment]
Idk how did composer allow it to install considering it requires php 7.4 and you have a previous version.

**Comment by Kirko95** [comment]
Thanks.. I've upgraded my php version and its working fine

**Comment by ConsoleTVs** [comment]
It's strange tho that composer didn't warn you or prevent you from installing it tho... 

Here's the requirement: https://github.com/Chartisan/PHP/blob/master/composer.json#L14
